# -*- coding: utf-8 -*-
"""Seed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/roshank1605A04/Seeds-Dataset/blob/master/Seed.ipynb

**Importing Libraries**
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

"""**Importing the dataset**"""

data = pd.read_csv('./seed.csv')
print(data.shape)
data.head()

data.isnull().sum()

data.describe()

data['TYPE'].value_counts()

"""**Splitting the data**"""

x = data.iloc[:,:7]
y = data.iloc[:,7]

print(x.shape)
print(y.shape)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0,shuffle= True)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)

model.predict(x_test)

print("training accuracy :", model.score(x_train, y_train))
print("testing accuracy :", model.score(x_test, y_test))

from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1','2'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('seeds.png')
Image(graph.create_png())

feature_cols = ['AREA', 'PERIMETER', 'COMPACTNESS', 'LENGTH	','WIDTH','	ASSYMMETRY_COEFFICIENT','GROOVE_LENGTH	']

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)

from sklearn import metrics
clf = DecisionTreeClassifier(criterion="entropy")
# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True, feature_names = feature_cols,class_names=['0','1','2'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('seed1.png')
Image(graph.create_png())